---
- name: install apache
  apt: name=apache2 state=present

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: create virtual host file
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}

- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}
  notify:
  - restart apache2


